name: CI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  store-submission:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Move submission to student directory
        run: |
          STUDENT=$(echo ${{ github.event.pull_request.user.login }})
          mkdir -p submissions/$STUDENT
          # Assuming the submission files are in a directory named `submission`
          mv submission/* submissions/$STUDENT/
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add submissions/$STUDENT
          git commit -m "Store submission from $STUDENT"
          git push origin main

  update-readme:
    needs: run-tests
    if: ${{ needs.run-tests.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Identify challenge name
        id: extract_challenge_name
        run: |
          CHALLENGE_NAME=$(echo ${{ github.event.pull_request.head.ref }} | sed 's/.*\///')
          echo "Challenge name is $CHALLENGE_NAME"
      - name: Add badge to README
        run: |
          echo "![Challenge Completed](https://img.shields.io/badge/Challenge%20Completed-$CHALLENGE_NAME-brightgreen)" >> README.md
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Add challenge completion badge"
          git push origin main